// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEHQnsXr6jrtirFVfmgM2eNXnVUK7Z79Q',
    appId: '1:257419506863:web:e5736f6f4abd04bae6505a',
    messagingSenderId: '257419506863',
    projectId: 'trackizer-30ecc',
    authDomain: 'trackizer-30ecc.firebaseapp.com',
    storageBucket: 'trackizer-30ecc.appspot.com',
    measurementId: 'G-PHMSNHGKJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbzzv4yNswvFYsdEnHy8_zW5C5uveLyxU',
    appId: '1:257419506863:android:db678f187b735e8ee6505a',
    messagingSenderId: '257419506863',
    projectId: 'trackizer-30ecc',
    storageBucket: 'trackizer-30ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK9NFz1vn5xCBiEiU24GEz9UnKCJ4Gsbk',
    appId: '1:257419506863:ios:74c4a2f153f9285ee6505a',
    messagingSenderId: '257419506863',
    projectId: 'trackizer-30ecc',
    storageBucket: 'trackizer-30ecc.appspot.com',
    iosBundleId: 'com.example.trackizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK9NFz1vn5xCBiEiU24GEz9UnKCJ4Gsbk',
    appId: '1:257419506863:ios:74c4a2f153f9285ee6505a',
    messagingSenderId: '257419506863',
    projectId: 'trackizer-30ecc',
    storageBucket: 'trackizer-30ecc.appspot.com',
    iosBundleId: 'com.example.trackizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEHQnsXr6jrtirFVfmgM2eNXnVUK7Z79Q',
    appId: '1:257419506863:web:8e2bce18afa1d88be6505a',
    messagingSenderId: '257419506863',
    projectId: 'trackizer-30ecc',
    authDomain: 'trackizer-30ecc.firebaseapp.com',
    storageBucket: 'trackizer-30ecc.appspot.com',
    measurementId: 'G-3H2MQC4CBP',
  );
}
